name: Java CI with Maven

on:
  push:
    branches:
      - main  # This will trigger the CI workflow when you push to the 'main' branch
  pull_request:
    branches:
      - main  # This will trigger the workflow for pull requests to the 'main' branch

jobs:
  build:
    runs-on: ubuntu-latest  # The operating system for the CI environment

    steps:
    # Check out the code from GitHub
    - name: Checkout code
      uses: actions/checkout@v2

    # Set up JDK (we'll use JDK 11, but you can change the version if needed)
    - name: Set up JDK 11
      uses: actions/setup-java@v2
      with:
        java-version: '11'

    # Build the project using Maven
    - name: Build with Maven
      run: mvn clean install

    # Run tests using Maven
    - name: Run tests
      run: mvn test
